# version: "3.9"

services:
  migrate:
    networks:
      - payslip-application
    restart: no
  web:
    environment:
      NODE_ENV: "production"
    networks:
      - payslip-application
    restart: always
    command: sh -c "node server.js"
  database:
    networks:
      - payslip-application
    restart: always
  nginx:
    image: nginx:alpine
    ports:
     - "${LOCAL_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - payslip-application
    depends_on:
      - web
    restart: always

networks:
  payslip-application:
    name: payslip-application
    driver: bridge
